### PR TITLE
Fix filter reset on data update

### LINKED ISSUE #41: Make query params and table filters play nice
Right now only the tags and time range use query params, and that filtering overrides the table filtering.  Need to make sure that the table remains filtered even after query params change.

### PR DESCRIPTION
**Pull request by k3KAW8Pnf7mkmdSMPHz27**
Fixes #41. See [the specs for for (slightly) more information about the option](https://react-table.tanstack.com/docs/api/useFilters#table-options).

Refs. #57.

### CODE REVIEW

File: statusboard/src/components/PageContents/PageContents.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import React from 'react';
 import { Route, Switch } from 'react-router-dom';
 import About from '../../pages/About/About';
-import Projects from '../../pages/Projects/Projects';
+import Projects from '../../pages/Projects/Projects.tsx';
```
Comment (mmazanec22) [inline statusboard/src/components/PageContents/PageContents.js:4]: This shouldn't need to specify `.tsx`

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply statusboard/src/components/PageContents/PageContents.js:4]: I am getting

```
ESLint: Unable to resolve path to module '../../pages/Projects/Projects'.(import/no-unresolved)`.
ESLint: Unable to resolve path to module '../../pages/Projects/Projects'.(import/no-unresolved)
```

And as far as I can tell I am using the correct ESLint config file and [I believe it is based on the airbnb extension](https://stackoverflow.com/questions/59265981/typescript-eslint-missing-file-extension-ts-import-extensions)?

https://github.com/codeforamerica/brigade-project-index-statusboard/blob/9d039a4a6b85aef073522dae004f746f51526c6e/statusboard/.eslintrc.json#L2

Would you like me to revert it or change the ESLint config?

**Review by mmazanec22 — APPROVED** [review]
